-- 生成测试数据 - 完整版
SET NAMES utf8mb4;

-- 步骤1: 清理旧的测试数据
DELETE FROM article_comment WHERE article_id > 0;
DELETE FROM article WHERE id > 0;
DELETE FROM user WHERE username LIKE 'test_%';

-- 步骤2: 生成500个测试用户
INSERT IGNORE INTO user (username, password, nickname, email, user_pic, create_time, update_time)
SELECT 
  CONCAT('test_user_', t1.n * 25 + t2.n), 
  '123456', 
  CONCAT('user_', t1.n * 25 + t2.n), 
  CONCAT('user', t1.n * 25 + t2.n, '@test.com'), 
  '', 
  NOW(), 
  NOW()
FROM (
  SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
  SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
  SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL
  SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
) t1
CROSS JOIN (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
  SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL
  SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
  SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL
  SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
) t2
LIMIT 500;

-- 步骤3: 生成10000篇文章（使用现有的用户ID 1,2,3,4,5,6,9,10,15）
INSERT INTO article (title, content, cover_img, state, category_id, create_user, create_time, update_time, view_count, like_count, collect_count, is_hot, is_best, comment_count, is_delete)
SELECT 
  CONCAT('Article_', @row := @row + 1),
  CONCAT('Content of article ', @row),
  '',
  IF(RAND() > 0.3, '已发布', '草稿'),
  ELT(FLOOR(1 + RAND() * 4), 2, 3, 4, 8),  -- 使用存在的分类ID
  ELT(FLOOR(1 + RAND() * 9), 1, 2, 3, 4, 5, 6, 9, 10, 15),  -- 使用存在的用户ID
  NOW(), 
  NOW(),
  FLOOR(RAND() * 10000), 
  FLOOR(RAND() * 5000), 
  FLOOR(RAND() * 2000),
  IF(RAND() < 0.1, 1, 0), 
  IF(RAND() < 0.05, 1, 0), 
  FLOOR(RAND() * 500), 
  0
FROM 
  (SELECT @row := 0) init,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t1,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t2,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t3,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t4,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t5,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) t6
LIMIT 10000;

-- 步骤4: 生成50000条评论
INSERT INTO article_comment (article_id, user_id, content, create_time, is_delete, audit_status)
SELECT 
  FLOOR(1 + RAND() * 10000),
  ELT(FLOOR(1 + RAND() * 9), 1, 2, 3, 4, 5, 6, 9, 10, 15),
  ELT(FLOOR(1 + RAND() * 6), 'Good', 'Nice', 'Thanks', 'Great', 'Helpful', 'Useful'),
  NOW(), 
  0, 
  2
FROM 
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t1,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t2,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t3,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t4,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t5,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) t6,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t7,
  (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t8
LIMIT 50000;

-- 步骤5: 查看统计结果
SELECT 'users' as table_name, COUNT(*) as count FROM user
UNION ALL 
SELECT 'articles', COUNT(*) FROM article
UNION ALL 
SELECT 'comments', COUNT(*) FROM article_comment;